services:
  kloset-db:
    image: pgvector/pgvector:pg18
    container_name: kloset-keeper-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - kloset-db-data:/var/lib/postgresql
  kloset-valkey:
    image: valkey/valkey:9.0.1-alpine3.23
    container_name: kloset-keeper-valkey
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - kloset-valkey-data:/data

volumes:
  kloset-db-data:
  kloset-valkey-data: